### ISSUE TITLE
Eval sheet un-readable

### ISSUE THREAD

**Issue by nikander100** [FreekBes/dark_intra#1]
When on the evalsheet the text is the same color as the background

**Comment by FreekBes** [comment]
I hope to have it fixed in version 1.1.1. Couldn't test the changes in this update properly yet, since I only had a local HTML version of the eval sheet lying around, which didn't stylize properly.

Let me know if any issues on the eval sheet still appear. It is very likely. To make things smoother, save the page the error occurs as HTML, zip the created HTML and the created folder with necessary files (suchs as stylesheets and JS scripts) and attach this ZIP file here or send it to me over Slack (Intra name = fbes).

**Comment by FreekBes** [comment]
Looks like with most evals this bug has been fixed. If it appears again, please re-open this issue.
